version: '3.8'

services:
  step-daddy-live-hd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3232}:${PORT:-3232}"
    environment:
      - PORT=${PORT:-3232}
      - API_URL=${API_URL:-http://localhost:3232}
      - BACKEND_HOST_URI=${BACKEND_HOST_URI:-}
      - DADDYLIVE_URI=${DADDYLIVE_URI:-https://thedaddy.click}
      - PROXY_CONTENT=${PROXY_CONTENT:-TRUE}
      - SOCKS5=${SOCKS5:-}
      - WORKERS=${WORKERS:-6}
    restart: unless-stopped
    env_file:
      - .env