version: '3.8'

services:
  step-daddy-live-hd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT:-3000}
      - API_URL=${API_URL:-}
      - BACKEND_HOST_URI=${BACKEND_HOST_URI:-}
      - DADDYLIVE_URI=${DADDYLIVE_URI:-https://thedaddy.click}
      - PROXY_CONTENT=${PROXY_CONTENT:-TRUE}
      - SOCKS5=${SOCKS5:-}
      - WORKERS=${WORKERS:-4}
    restart: unless-stopped
    env_file:
      - .env