version: '3.8'

services:
  step-daddy-live-hd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3232}:${PORT:-3232}"
      - "${BACKEND_PORT:-8005}:${BACKEND_PORT:-8005}"
    environment:
      - PORT=${PORT:-3232}
      - BACKEND_PORT=${BACKEND_PORT:-8005}
      - API_URL=${API_URL:-http://192.168.4.5:3232}
      - DADDYLIVE_URI=${DADDYLIVE_URI:-https://thedaddy.click}
      - PROXY_CONTENT=${PROXY_CONTENT:-TRUE}
      - SOCKS5=${SOCKS5:-}
      - WORKERS=${WORKERS:-6}
    network_mode: host
    restart: unless-stopped