version: '3.8'

services:
  step-daddy-live-hd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3232}:${PORT:-3232}"
      - "${BACKEND_PORT:-8005}:${BACKEND_PORT:-8005}"
    environment:
      - PORT=${PORT:-3232}
      - BACKEND_PORT=${BACKEND_PORT:-8005}
      - BACKEND_URI=${BACKEND_URI:-http://localhost:${BACKEND_PORT:-8005}}
      - API_URL=${API_URL}  # Let rxconfig.py handle the default
      - DADDYLIVE_URI=${DADDYLIVE_URI:-https://thedaddy.click}
      - PROXY_CONTENT=${PROXY_CONTENT:-TRUE}
      - SOCKS5=${SOCKS5:-}
      - WORKERS=${WORKERS:-6}
      - REFLEX_ENV=prod
      - REFLEX_FRONTEND_ONLY=true
      - REFLEX_SKIP_COMPILE=1
    networks:
      - step-daddy-network
    restart: unless-stopped

networks:
  step-daddy-network:
    driver: bridge