version: '3.8'

services:
  stepdaddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3232:3232"  # Frontend port
      - "8005:8005"  # Backend port for WebSocket
    environment:
      - API_URL=http://localhost:3232
      - BACKEND_PORT=8005
      - REFLEX_ENV=prod
      - REFLEX_SKIP_COMPILE=1
      - CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./StepDaddyLiveHD:/app/StepDaddyLiveHD
    restart: unless-stopped
    networks:
      - stepdaddy-net

networks:
  stepdaddy-net:
    driver: bridge